title: Ethan Zhao
logo: /assets/img/logo.png
email: ethanz01@student.ubc.ca
description: A UBC Masters student researching NLP, RAG
show_downloads: false
google_analytics: G-ZLK2GHB055
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  # - name: Google Scholar
  #   icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
  #   link: https://scholar.google.com/citations?user=zR6afi8AAAAJ
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Ezepheros
  - name: LinkedIn
    icon: |
      <svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 24 24" width="1em" height="1em" fill="currentColor">
        <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.026-3.037-1.852-3.037-1.854 0-2.137 1.445-2.137 2.938v5.668H9.352V9h3.414v1.561h.049c.476-.899 1.637-1.848 3.372-1.848 3.604 0 4.268 2.372 4.268 5.455v6.284zM5.337 7.433c-1.144 0-2.068-.927-2.068-2.07 0-1.144.924-2.069 2.068-2.069s2.069.925 2.069 2.069c0 1.143-.925 2.07-2.069 2.07zm1.777 13.019H3.559V9h3.555v11.452z"/>
      </svg>
    link: www.linkedin.com/in/ethan-zhao-576355178
  # - name: Blog
  #   icon: <i class="fa-solid fa-pen"></i>
  #   link: https://www.bodunhu.com/blog/
  # - name: Project Repository
  #   icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
  #   link: https://github.com/BDHU/minimalist

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error â€”
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]

plugins:
  - jekyll-remote-theme

remote_theme: BDHU/minimalist